[package]
name = "rust-multi-db-tenant"
version = "0.1.0"
edition = "2021"

[profile.dev]
incremental = true
opt-level = 0      # No optimization for faster build times
debug = true       # Include debug symbols
lto = false        # Disable Link Time Optimization for faster linking
panic = 'unwind'   # Faster panic handling

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mongodb = { version = "2.8" }
bson = "2.8"  # Add this separately
dotenv = "0.15.0"
moka = { version = "0.10.0", features = ["future"] }
futures = "0.3"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
peak_alloc = "0.2.0"
